### ISSUE TITLE
peer review 1

### ISSUE THREAD

**Issue by YHuUBC** [xXJohamXx/movie_DASHboard#1]
- This is a great app for movie lovers! It functions very well; I like the two sliders for selecting the rating and runtime ranges. Very helpful function. 
- Some minor suggestions for your reference:
1. what did the select box do in the 'Explore the movies' section? I tried to select it, but it seems to change nothing in the plot or table.
![image](https://user-images.githubusercontent.com/112221943/226254567-20928fd0-a2ec-4ed7-b450-17532507fad6.png)
2. may I ask what the recommendations' numbers represent? A user might need some clarification seeing the numbers.
![image](https://user-images.githubusercontent.com/112221943/226254743-9016a889-e1b5-4a80-9613-75f4294e7be8.png)

Great app in general. A pleasure to review it.

**Comment by xXJohamXx** [comment]
1. The check box is just there if you want to select a specific row, once selected they can be deleted. Improving the data table functionality is something else that I plan to work on in the future. 

2. The numbers in the recommendations column are movie id's I planed to replace them with titles but wanted to make sure the app deployed properly first. The recommendations column now contains movie names and not numbers.
